Controllers/TiendaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bookstore.Models.Interfaces;
using bookstore.Models;

namespace bookstore.Controllers
{
    public class TiendaController : Controller
    {
        private IDBAccess _accesoDB;

        public TiendaController(IDBAccess servicioDBInyect)
        {
            this._accesoDB = servicioDBInyect;
        }


        [HttpGet]                                         
        public async Task<IActionResult> Libros(String id) 
        {
            Materia materia = new Materia();   

            if (String.IsNullOrEmpty(id))  
            {
                materia.IdMateria = 5;
                materia.IdMateriaPadre = 0;
                materia.NombreMateria = "Informatica;informatica";
            }
            else
            {
                materia.IdMateria = System.Convert.ToInt32(id.Split("")[0]);
                materia.IdMateriaPadre = System.Convert.ToInt32(id.Split("")[1]);
                materia.NombreMateria = id.Split("")[2].ToString();
            }     
            List<Libro> libros = await this._accesoDB.DevolverLibros(materia.IdMateria, null);
            return View(libros);
        }

        [HttpGet]
        public async Task<IActionResult> MostrarLibro([FromQuery]String isbn, [FromQuery]String idmateria) 
        {
            List<Libro> libros = await this._accesoDB.DevolverLibros(System.Convert.ToInt32(idmateria), isbn);
            Libro libro = libros.Single<Libro>();
            return View(libro);  
        }

        [HttpPost]
        public async Task<IActionResult> BuscadorLibros(String busqueda, String opcion) 
        {
            List<Libro> libros = await this._accesoDB.BuscarLibros(opcion, busqueda);
            return View("Libros", libros); 
        }
    }
}

Views/Shared/_Layout.cshtml
@using bookstore.Models.Interfaces;
@inject IControlSession _servicioSession
@{Cliente _clienteLogin = this._servicioSession.RecuperarSession<Cliente>("datoscliente");}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - asp.net-web-bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-9" style="background-color: black"></div>
                <div class="col-3" style="background-color: black">
                    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                        <a href="#" class="btn btn-dark btn-sm">
                            <img src="~/images/botonMINIcontacto.png" />
                        </a>
                        @if (_clienteLogin != null)
                        {
                            <a asp-controller="Cliente" asp-action="MiPerfil" class="btn btn-dark btn-sm">
                                Bienvenido: @_clienteLogin.Nombre,@_clienteLogin.Apellidos,(@_clienteLogin.CredencialesCliente.Email)
                            </a>
                        }
                        else    
                        {
                            <a asp-controller="Cliente" asp-action="Login" class="btn btn-dark btn-sm">
                                <img src="~/images/botonMINIlogin.png" />
                            </a>
                        }
                    </div>
                </div>
            </div>
            <div class="row" style="background-color: rgb(237,237,237)">
                <div class="col-md-4">
                    <img src="~/images/logo_Agapea_layout.png" />
                </div>
                <div class="col-md-6">
                    <form asp-controller="Tienda" asp-action="BuscarLibros" method="post">
                        <div class="input-group mb-3">
                            <input type="search" name="cajaTexto" class="form-control" placeholder="Buscar por libro, autor, ISBN..."
                                   aria-label="Buscar por libro,autor,isbn..." aria-describedby="botonBuscar" />
                            <div class="input-group-append">
                                <a class="btn btn-outline-primary" id="botonBuscar"
                                   onclick="javascript: document.forms[0].submit()">
                                    <img src="~/images/boton_BuscarLibros.png" />
                                </a>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="radio" class="form-check-input" name="optradio" value="Titulo">
                                    Titulo
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="radio" class="form-check-input" name="optradio" value="ISBN">
                                    ISBN
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="radio" class="form-check-input" name="optradio" value="Autor">
                                    Autor
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="radio" class="form-check-input" name="optradio" value="Editorial">
                                    Editorial
                                </label>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-2">
                    <a asp-action="MostrarPedido" asp-controller="Pedido" class="btn btn-light">
                        <img src="~/images/boton_mini_carrito.png" />
                        <span class="badge badge-danger">0</span>
                        <small>Total:</small>
                        <img src="~/images/boton_flecha_minicarrito.png" />
                    </a>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-2">
                <!-- treeview de materias de libros -->
                @await Component.InvokeAsync("PanelListaMaterias")
            </div>
            <div class="col-10">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col">
                    <small>&copy;  Agapea CLASE S.A. 2020. Reservados todos los derechos </small>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_VistaItemPedido.cshtml
@model ItemPedido
<table class="table table-borderless">
    <tr>
        <td rowspan="2">
            <img src="~/images/imagenLibro.png" />
        </td>
        <td><label><h4>@Model.LibroPedido.Titulo</h4></label></td>
        <td>
            <a asp-controller="Pedido" asp-action="EliminarLibroPedido"
               asp-all-route-data="@(new Dictionary<String, String> { { "id", Model.LibroPedido.ISBN } })"
               style="color:red"
               class="btn btn-light">
                <strong>X</strong>
            </a>
        </td>
    </tr>
    <tr>
        <td>
            <a asp-controller="Pedido" asp-action="RestarCantidad" asp-all-route-data="@(new Dictionary<String, String> { { "id", Model.LibroPedido.ISBN } })" class="btn btn-primary"id="botonMenos-@Model.LibroPedido.ISBN"> - </a>
            <label id="ISBN-@Model.LibroPedido.ISBN">@Model.CantidadLibro</label>
            <a asp-controller="Pedido" asp-action="SumarCantidad" asp-all-route-data="@(new Dictionary<String, String> { { "id", Model.LibroPedido.ISBN} })" class="btn btn-primary"> + </a>
            <label>x</label>
            <label style="color:red">@Model.LibroPedido.Precio €</label>
        </td>
        <td>
            <label style="color:red">@(Model.CantidadLibro * Model.LibroPedido.Precio)</label>
        </td>
    </tr>
</table>

Views/Shared/_VistaParcialMiniDireccion.cshtml
@model Direccion
<div class="card mb-3">
    <div class="row no-gutters">
        <div class="col-md-2">
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="esPrincipal">
                <label class="form-check-label" for="exampleCheck1">Direccion Principal</label>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Calle CP: @Model.CP, @Model.Municipio.NombreMunicipio ( @Model.Provincia.NombreProvincia )</h5>
                <p class="card-text"><small class="text-muted">Direccion id: @Model.IdDireccion</small></p>
            </div>
        </div>
        <div class="col-md-2">
            <a class="btn btn-sm btn-light"
               id="@(String.Concat("btnEditarDireccion_",Model.IdDireccion))"
               asp-controller="Cliente"
               asp-action="Editar"
               asp-all-route-data="@(new Dictionary<String, String> { { "id", Model.IdDireccion} })">
               <img src="~/images/boton_EditarDireccion_MisDatosEnvio.png" />
            </a>
            <a class="btn btn-sm btn-light"
               id="@(String.Concat("btnEliminarDireccion_",Model.IdDireccion))"
               asp-controller="Cliente"
               asp-action="Eliminar"
               asp-all-route-data="@(new Dictionary<String, String> { { "id", Model.IdDireccion} })">
               <img src="~/images/boton_EliminarDireccion_MisDatosEnvio.png" />
            </a>
        </div>
    </div>
</div>

Views/Shared/_VistaParcialMiniLibro.cshtml
@model Libro
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <img class="card-img" src="~/images/imagenLibro.png" />
            <a class="btn btn-primary"
               asp-controller="Pedido" asp-action="AddLibroPedido"
               asp-all-route-data="@(new Dictionary<String, String> { { "id", Model.ISBN } })">
               <img src="~/images/BotonComprar.png" />
            </a>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">
                    <a class="card-link"
                       asp-controller="Tienda" asp-action="MostrarLibro"
                       asp-all-route-data="@(new Dictionary<String, String> { { "isbn", Model.ISBN },{ "idmateria", Model.IdMateria.ToString() } })">
                        @Model.Titulo
                    </a>
                </h5>
                <p class="card-text">@Model.Autores</p>
                <p class="card-text">@Model.Editorial</p>
                <p class="card-text"><small class="text-muted">@Model.NumeroPaginas paginas</small></p>
                <p class="card-text"><b>@Model.Precio €</b></p>
            </div>
        </div>
    </div>
</div>

Views/Shared/_VistaParcialTupla3Libros.cshtml
@model List<Libro>
<div class="card-group">
    @foreach (Libro libro in Model) 
    {
        <partial name="_VistaParcialMiniLibro" model="libro" />
    }
</div>